apiVersion: v1
kind: Pod
metadata:
  name: densify
spec:
  initContainers:
  - name: azure-token
    image: densify/azure-rest-api-token:latest
    imagePullPolicy: Always
    env:
    - name: ENTRA_SERVICE_PRINCIPAL
      value: "/home/densify/.azmon/app.json"
    - name: AZURE_RESOURCE
      value: "https://prometheus.monitor.azure.com"
    - name: BEARER_TOKEN_FILE
      value: "/home/densify/.tokens/token"
    volumeMounts:
    - mountPath: /home/densify/.azmon
      name: azmon
      readOnly: true
    - mountPath: /home/densify/.tokens
      name: tokens
  containers:
  - image: densify/container-optimization-data-forwarder:4-beta
    imagePullPolicy: Always
    name: data-forwarder
    env:
    - name: CONFIG_TYPE
      value: "yaml"
    - name: PROMETHEUS_OAUTH_TOKEN
      value: "/home/densify/.tokens/token"
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /home/densify/.tokens
      name: tokens
  volumes:
  - name: config
    configMap:
      name: densifyconf
      items:
        - key: config.yaml
          path: config.yaml
  - name: tokens
    emptyDir: {}
  - name: azmon
    secret:
      secretName: azmon
  restartPolicy: Never
