apiVersion: v1
kind: Pod
metadata:
  name: densify
spec:
  containers:
  - image: densify/container-optimization-data-forwarder:4-beta
    imagePullPolicy: Always
    name: data-forwarder
    env:
    - name: CONFIG_TYPE
      value: "yaml"
    volumeMounts:
    - mountPath: /config
      name: config
  volumes:
  - name: config
    configMap:
      name: densifyconf
      items:
        - key: config.yaml
          path: config.yaml
  restartPolicy: Never
